export default {
	'zotero.appName': 'Zotero',
	'general.etAl': 'et al.',
	'general.back': 'Back',
	'general.thanksForHelpingImprove': 'Thanks for helping to improve %S!',
	'general.tryAgain': 'Try Again',
	'general.updateAvailable': 'Update Available',
	'general.copyToClipboard': 'Copy to Clipboard',
	'general.finished': 'Finished',
	'general.checkForUpdates': 'Check for Updates',
	'general.keys.cmdShift': 'Cmd+Shift+',
	'general.clear': 'Clear',
	'general.failed': 'Failed',
	'general.restartLater': 'Restart later',
	'general.unknownErrorOccurred': 'An unknown error occurred.',
	'general.dontShowAgainFor': 'Don’t show again today;Don’t show again for %1$S days',
	'general.permissionDenied': 'Permission Denied',
	'general.checkForUpdate': 'Check for Update',
	'general.moreInformation': 'More Information',
	'general.quitApp': 'Quit %S',
	'general.errorHasOccurred': 'An error has occurred.',
	'general.and': 'and',
	'general.isUpToDate': '%S is up to date.',
	'general.seeForMoreInformation': 'See %S for more information.',
	'general.success': 'Success',
	'general.submitted': 'Submitted',
	'general.character.plural': 'characters',
	'general.locate': 'Locate…',
	'general.restartNow': 'Restart now',
	'general.pleaseRestart': 'Please restart %S.',
	'general.quit': 'Quit',
	'general.hide': 'Hide',
	'general.browserIsOffline': '%S is currently in offline mode.',
	'general.error': 'Error',
	'general.import': 'Import',
	'general.warning': 'Warning',
	'general.yes': 'Yes',
	'general.useDefault': 'Use Default',
	'general.fix': 'Fix…',
	'general.restartRequiredForChanges': '%S must be restarted for the changes to take effect.',
	'general.accessDenied': 'Access Denied',
	'general.continue': 'Continue',
	'general.dontShowAgain': 'Don’t Show Again',
	'general.copy': 'Copy',
	'general.keys.ctrlShift': 'Ctrl+Shift+',
	'general.create': 'Create',
	'general.export': 'Export',
	'general.noUpdatesFound': 'No Updates Found',
	'general.restartRequired': 'Restart Required',
	'general.actionCannotBeUndone': 'This action cannot be undone.',
	'general.pdf': 'PDF',
	'general.remove': 'Remove',
	'general.cancel': 'Cancel',
	'general.tryLater': 'Try Later',
	'general.operationInProgress.waitUntilFinishedAndTryAgain': 'Please wait until it has finished and try again.',
	'general.processing': 'Processing',
	'general.disable': 'Disable',
	'general.restartApp': 'Restart %S',
	'general.enable': 'Enable',
	'general.showDirectory': 'Show Directory',
	'general.passed': 'Passed',
	'general.invalidResponseServer': 'Invalid response from server.',
	'general.reset': 'Reset',
	'general.nMegabytes': '%S MB',
	'general.numMore': '%S more…',
	'general.serverError': 'The server returned an error. Please try again.',
	'general.upgrade': 'Upgrade',
	'general.open': 'Open %S',
	'general.openPreferences': 'Open Preferences',
	'general.describeProblem': 'Briefly describe the problem:',
	'general.pleaseRestartAndTryAgain': 'Please restart %S and try again.',
	'general.operationInProgress.waitUntilFinished': 'Please wait until it has finished.',
	'general.dontShowWarningAgain': 'Don\'t show this warning again.',
	'general.notNow': 'Not Now',
	'general.item': 'Item',
	'general.restartRequiredForChange': '%S must be restarted for the change to take effect.',
	'general.character.singular': 'character',
	'general.operationInProgress': 'A Zotero operation is currently in progress.',
	'general.no': 'No',
	'general.delete': 'Delete',
	'general.openDocumentation': 'Open Documentation',
	'general.tryAgainLater': 'Please try again in a few minutes.',
	'general.install': 'Install',
	'general.yellow': 'Yellow',
	'general.red': 'Red',
	'general.green': 'Green',
	'general.blue': 'Blue',
	'general.purple': 'Purple',
	'general.orange': 'Orange',
	'general.magenta': 'Magenta',
	'general.gray': 'Gray',
	'general.showInLibrary': 'Show in Library',
	'general.insert': 'Insert',
	'noteEditor.blockquote': 'Block Quote',
	'noteEditor.mathBlock': 'Math Block',
	'noteEditor.italic': 'Italic',
	'noteEditor.cut': 'Cut',
	'noteEditor.orderedList': 'Numbered List',
	'noteEditor.alignCenter': 'Align Center',
	'noteEditor.replaceNext': 'Replace',
	'noteEditor.bulletList': 'Bulleted List',
	'noteEditor.replaceAll': 'Replace All',
	'noteEditor.showItem': 'Show Item',
	'noteEditor.heading1': 'Heading 1',
	'noteEditor.leftToRight': 'Left to Right',
	'noteEditor.enterLink': 'Enter Link',
	'noteEditor.paste': 'Paste',
	'noteEditor.insertCitation': 'Insert Citation',
	'noteEditor.copy': 'Copy',
	'noteEditor.bold': 'Bold',
	'noteEditor.heading3': 'Heading 3',
	'noteEditor.editInWindow': 'Edit in a Separate Window',
	'noteEditor.previous': 'Previous',
	'noteEditor.returnToNotesList': 'Return to Notes List',
	'noteEditor.updateNotice': 'This note was edited with a newer version of %1$S.\nPlease update %1$S to make changes.',
	'noteEditor.heading2': 'Heading 2',
	'noteEditor.findAndReplace': 'Find and Replace',
	'noteEditor.monospaced': 'Monospaced',
	'noteEditor.insertLink': 'Insert Link',
	'noteEditor.align': 'Align',
	'noteEditor.showOnPage': 'Show on Page',
	'noteEditor.addCitation': 'Add Citation',
	'noteEditor.removeCitation': 'Hide Citation',
	'noteEditor.alignRight': 'Align Right',
	'noteEditor.replace': 'Replace',
	'noteEditor.annotationsWithDate': 'Annotations (%S)',
	'noteEditor.alignLeft': 'Align Left',
	'noteEditor.clearFormatting': 'Clear Formatting',
	'noteEditor.unlink': 'Unlink',
	'noteEditor.goToPage': 'Go to Page',
	'noteEditor.underline': 'Underline',
	'noteEditor.next': 'Next',
	'noteEditor.more': 'More',
	'noteEditor.set': 'Set',
	'noteEditor.paragraph': 'Paragraph',
	'noteEditor.editCitation': 'Edit Citation',
	'noteEditor.rightToLeft': 'Right to Left',
	'noteEditor.find': 'Find',
	'noteEditor.formatText': 'Format Text',
	'noteEditor.highlightText': 'Highlight Text',
	'noteEditor.textColor': 'Text Color',
	'noteEditor.removeColor': 'Remove Color',
	'noteEditor.strikethrough': 'Strikethrough',
	'noteEditor.subscript': 'Subscript',
	'noteEditor.superscript': 'Superscript',
	'noteEditor.edit': 'Edit',
	'noteEditor.applyAnnotationColors': 'Apply Annotation Colors',
	'noteEditor.removeAnnotationColors': 'Remove Annotation Colors',
	'noteEditor.addCitations': 'Show Annotation Citations',
	'noteEditor.removeCitations': 'Hide Annotation Citations',
	'noteEditor.image': 'Image',
	'noteEditor.math': 'Math',
	'noteEditor.table': 'Table',
	'noteEditor.citation': 'Citation',
	'noteEditor.insertRowBefore': 'Insert Row Above',
	'noteEditor.insertRowAfter': 'Insert Row Below',
	'noteEditor.insertColumnBefore': 'Insert Column Left',
	'noteEditor.insertColumnAfter': 'Insert Column Right',
	'noteEditor.deleteRow': 'Delete row',
	'noteEditor.deleteColumn': 'Delete column',
	'noteEditor.deleteTable': 'Delete table',
	'noteEditor.insertImage': 'Insert Image',
	'noteEditor.insertTable': 'Insert Table',
	'noteEditor.insertMath': 'Insert Math Block',
	'noteEditor.a11yLinkPopupAppearedAlert': 'Link popup appeared. Use Shift-Tab to navigate it.'
};
